[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]

[rpc_endpoints]
zsnail = "http://34.122.156.185:8545"